/* ---------------- variables globales ------------------*/
var productos = [
    {
        nombre: "Cubrecama", 
        precio: 45100,
        stock: 15,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,50 x 1,90 mts",
        detalle2: "Cubrecama tejida tamaño king, color: Rosa",
        edadMin: 5,
        edadMax: 99,
        envio: true,
        img: "../images/products/cubrecamas/cubre-cama.jpg"
    },
    {
        nombre: "Alfombra", 
        precio: 25500,
        stock: 5,
        marca: "Cammon",
        categoria: "Decoración",
        detalle1: "60 cm diámetro",
        detalle2: "Alfombra redonda, color rosa chicle, 100% algodón, con base antideslizante, 30mm pelo extra largo",
        edadMin: 1,
        edadMax: 99,
        envio: true,
        img: "../images/products/alfombras/alfombras-redondas/alfombra-redonda7.webp"
    },
    {
        nombre: "Alfombra", 
        precio: 65000,
        stock: 20,
        marca: "Camon",
        categoria: "Decoración",
        detalle1: "80 cm diámetro",
        detalle2: "Alfombra redonda, color crudo, Premium 100% algodón peinado con detalle de terminación.",
        edadMin: 1,
        edadMax: 99,
        envio: false,
        img: "../images/products/alfombras/otras/alfombra6.jpg"
    },
    {
        nombre: "Acolchado", 
        precio: 70000,
        stock: 25,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,60 x 1,90 mts",
        detalle2: "Acolchado tamaño king, color Rosa, Peso Aproximado: 3,650kg Funda Exterior 100% Algodón",
        edadMin: 1,
        edadMax: 99,
        envio: true,
        img: "../images/products/cubrecamas/cubre-cama-3.jpg"
    },
    {
        nombre: "Acolchado", 
        precio: 55000,
        stock: 15,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,50 x 1,90 mts",
        detalle2: "Acolchado tamaño king, color: Verde agua, Peso Aproximado: 3,650kg Funda Exterior 100% Algodón Relleno 100% Plumas",
        edadMin: 1,
        edadMax: 99,
        envio: true,
        img: "../images/products/acolchados/acolchado-3.jpg"
    },
    {
        nombre: "Sábanas", 
        precio: 22000,
        stock: 8,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "140x190x30cm",
        detalle2: "Juego de sábanas color blanco, Para cama de 2 1/2 plazas Colchón de Sábana 180 hilos 100% Algodón Incluye 2 fundas de almohada 45x80cm",
        edadMin: 1,
        edadMax: 99,
        envio: true,
        img: "../images/products/sabanas/sabanas.jpg"
    },
    {
        nombre: "Toalla de mano", 
        precio: 7800,
        stock: 20,
        marca: "Camon",
        categoria: "Baño",
        detalle1: "20cm x 40cm",
        detalle2: "Toalla de mano algodón 100%, color verde, peso 450 grs./m2 ",
        edadMin: 5,
        edadMax: 99,
        envio: true,
        img: "../images/products/toallas/toallas4.jpg"
    },
    {
        nombre: "Juego de toallas", 
        precio: 9000,
        stock: 10,
        marca: "Cammon",
        categoria: "Baño",
        detalle1: "20cm x 40cm",
        detalle2: "Juego de toalla y toallón, algodón 100%, color blanco, peso 520 grs./m2 ",
        edadMin: 0,
        edadMax: 99,
        envio: false,
        img: "../images/products/toallas/toallas1.webp"
    },
    {
        nombre: "Manta tramada", 
        precio: 35000,
        stock: 10,
        marca: "Camon",
        categoria: "Hogar",
        detalle1: "0.80 x 1,50 mts",
        detalle2: "Hecha con tramas de hilo de algodón tejido en colores mixtos, las mantas Cammon ofrecen calidez a tu hogar.",
        edadMin: 3,
        edadMax: 99,
        envio: true,
        img: "../images/products/mantas/manta1.webp"
    },
    {
        nombre: "Cubrecama", 
        precio: 33000,
        stock: 15,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,50 x 1,90 mts",
        detalle2: "Cubrecama tejida tamaño king, color: Rosa",
        edadMin: 3,
        edadMax: 99,
        envio: false,
        img: "../images/products/cubrecamas/cubre-cama-2.jpg"
    },
    {
        nombre: "Acolchado", 
        precio: 55200,
        stock: 15,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,50 x 1,90 mts",
        detalle2: "Cubrecama tamaño king, color: Verde, Peso Aproximado: 3,650kg Funda Exterior 100% Algodón",
        edadMin: 3,
        edadMax: 99,
        envio: true,
        img: "../images/products/acolchados/acolchado-5.jpg"
    },
    {
        nombre: "Cubrecama", 
        precio: 50300,
        stock: 15,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,50 x 1,90 mts",
        detalle2: "Cubrecama tamaño king, color: Verde",
        edadMin: 3,
        edadMax: 99,
        envio: true,
        img: "../images/products/cubrecamas/cubre-cama-4.jpg"
    },
    {
        nombre: "Acolchado", 
        precio: 45200,
        stock: 15,
        marca: "Camon",
        categoria: "Dormitorio",
        detalle1: "1,50 x 1,90 mts",
        detalle2: "Acolchado tamaño king, 100% algodón, color Verde inglés",
        edadMin: 5,
        edadMax: 99,
        envio: true,
        img: "../images/products/acolchados/acolchado.jpg"
    },
    {
        nombre: "Alfombra", 
        precio: 33600,
        stock: 15,
        marca: "Camon",
        categoria: "Decoración",
        detalle1: "1,20 x 1,40 mts",
        detalle2: "Alfombra de piel rectangular, color: blanco",
        edadMin: 5,
        edadMax: 99,
        envio: true,
        img: "../images/products/alfombras/otras/alfombra3.png"
    },
]